services:
  auth-service:
    build: ./services/auth-service
    ports: ["8001:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@auth-db:5432/auth_db
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql

  patient-service:
    build: ./services/patient-service
    ports: ["8002:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@patient-db:5432/patient_db
    depends_on:
      - patient-db

  patient-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    ports:
      - "5434:5432"
    volumes:
      - patient_postgres_data:/var/lib/postgresql

  provider-service:
    build: ./services/provider-service
    ports: ["8003:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@provider-db:5432/provider_db
    depends_on:
      - provider-db

  provider-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: provider_db
    ports:
      - "5435:5432"
    volumes:
      - provider_postgres_data:/var/lib/postgresql

  appointment-service:
    build: ./services/appointment-service
    ports: ["8004:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@appointment-db:5432/appointment_db
    depends_on:
      - appointment-db

  appointment-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointment_db
    ports:
      - "5436:5432"
    volumes:
      - appointment_postgres_data:/var/lib/postgresql

volumes:
  auth_postgres_data:
  patient_postgres_data:
  provider_postgres_data:
  appointment_postgres_data: