services:
  auth-service:
    build: ./services/auth-service
    ports: ["8001:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@auth-db:5432/auth_db
      SECRET_KEY: ${SECRET_KEY}
      TEMPORAL_HOST: temporal:7233
      TEMPORAL_NAMESPACE: default
      USER_TASK_QUEUE: user_creation_queue
      REDIS_URL: redis://redis:6379
      UPDATE_USER_ROLE_TASK_QUEUE: user_update_queue
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: users.events
      PATIENT_KAFKA_TOPIC: patients.events
      PROVIDER_KAFKA_TOPIC: providers.events
    depends_on:
      auth-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  auth-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports: ["5433:5432"]
    volumes:
      - auth_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  patient-service:
    build: ./services/patient-service
    ports: ["8002:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@patient-db:5432/patient_db
      SECRET_KEY: ${SECRET_KEY}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: patients.events
    depends_on:
      patient-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  patient-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    ports: ["5434:5432"]
    volumes:
      - patient_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patient_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  provider-service:
    build: ./services/provider-service
    ports: ["8003:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@provider-db:5432/provider_db
      SECRET_KEY: ${SECRET_KEY}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: providers.events
      USERS_KAFKA_TOPIC: users.events
    depends_on:
      provider-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  provider-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: provider_db
    ports: ["5435:5432"]
    volumes:
      - provider_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d provider_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  appointment-service:
    build: ./services/appointment-service
    ports: ["8004:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:password@appointment-db:5432/appointment_db
      SECRET_KEY: ${SECRET_KEY}
      TEMPORAL_HOST: temporal:7233
      TEMPORAL_NAMESPACE: default
      APPOINTMENT_TASK_QUEUE: appointment_validation_queue
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: appointments.events
    depends_on:
      appointment-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  appointment-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointment_db
    ports: ["5436:5432"]
    volumes:
      - appointment_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appointment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal:
    image: temporalio/auto-setup:latest
    ports: ["7233:7233"]
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=temporal-db
    depends_on:
      temporal-db:
        condition: service_healthy

  temporal-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: temporal_db
    ports: ["5437:5432"]
    volumes:
      - temporal_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d temporal_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal-ui:
    image: temporalio/ui:latest
    ports: ["8080:8080"]
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  temporal-workflow:
    build: ./services/temporal-workflow
    environment:
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - PATIENT_SERVICE_URL=http://patient-service:8000
      - PROVIDER_SERVICE_URL=http://provider-service:8000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8000
      - SYSTEM_EMAIL=admin@smarthealth.com
      - SYSTEM_PASSWORD=admin
      - AUTH_SERVICE_URL=http://auth-service:8000
      - USER_TASK_QUEUE=user_creation_queue
      - APPOINTMENT_TASK_QUEUE=appointment_validation_queue
      - UPDATE_USER_ROLE_TASK_QUEUE=user_update_queue
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - temporal
      - auth-service
      - patient-service
      - rabbitmq
      - provider-service
      - appointment-service

  redis:
    image: redis:latest
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1  # snapshot to disk every 60s if ≥1 key changed

  kafka:
    image: confluentinc/cp-kafka:latest
    ports: ["9092:9092"]
    environment:
      KAFKA_NODE_ID: 1                                                              # unique ID for this broker node
      KAFKA_PROCESS_ROLES: broker,controller                                        # KRaft: one node acts as both message broker (serves producer and consumer) and cluster controller (leader selection, manage metadata)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093         # ports kafka binds to inside the container, 9092 for clients, 9093 for controller-to-controller traffic (Kafka talking to itself.)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092                            # address kafka tells clients to connect to (other containers reach it by the docker service name)
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER                                  # which listener is reserved for controller traffic
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093                                 # list of controller nodes: nodeId@host:port (single node in dev)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                    # internal __consumer_offsets topic replication, 1 for single broker dev
      KAFKA_LOG_DIRS: /var/lib/kafka/data                                           # where kafka writes messages to disk
      CLUSTER_ID: ${CLUSTER_ID}                                         # KRaft requires a fixed cluster UUID — must stay same across restarts
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - kafka_data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports: ["8081:8081"]
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092   # which kafka to connect to
      SCHEMA_REGISTRY_HOST_NAME: schema-registry                  # hostname this registry advertises
    depends_on:
      kafka:
        condition: service_healthy

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports: ["9000:9000"]
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  analytics-service:
    build: ./services/analytics-service
    ports: ["8005:8000"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: appointments.events
      PATIENT_KAFKA_TOPIC: patients.events
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
      DATABASE_URL: postgresql://postgres:password@analytics-db:5432/analytics_db
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      analytics-db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # broker port, celery connects here
      - "15672:15672"  # management UI — http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  notification-service:
    build: ./services/notification-service
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//   # RabbitMQ connection string
      CELERY_RESULT_BACKEND: redis://redis:6379/0             # Redis stores task results
      DATABASE_URL: postgresql://postgres:password@notification-db:5432/notification_db
    depends_on:
      rabbitmq:
        condition: service_healthy
      notification-db:
        condition: service_healthy
      redis:
        condition: service_started

  notification-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports: ["5438:5432"]
    volumes:
      - notification_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      auth-service:
        condition: service_started
      patient-service:    
        condition: service_started
      provider-service:
        condition: service_started
      appointment-service:
        condition: service_started
      analytics-service:
        condition: service_started

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  #ui
      - "4317:4317"    # services send traces heree

  analytics-db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    ports: ["5439:5432"]
    volumes:
      - analytics_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 10



volumes:
  auth_postgres_data:
  patient_postgres_data:
  provider_postgres_data:
  appointment_postgres_data:
  temporal_postgres_data:
  redis_data:
  kafka_data:
  notification_postgres_data:
  analytics_postgres_data:
