"""normalize schema

Revision ID: 08913e0c1fe1
Revises: de9ed8d3beb0
Create Date: 2026-06-28 12:57:30.703954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08913e0c1fe1'
down_revision: Union[str, Sequence[str], None] = 'de9ed8d3beb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_specialties_id'), table_name='provider_specialties')
    op.drop_table('provider_specialties')
    op.drop_index(op.f('ix_specialties_id'), table_name='specialties')
    op.drop_table('specialties')
    op.add_column('providers', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_constraint(op.f('providers_email_key'), 'providers', type_='unique')
    op.drop_column('providers', 'email')
    op.drop_column('providers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('providers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('providers_email_key'), 'providers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('providers', 'created_at')
    op.create_table('provider_specialties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('provider_specialties_provider_id_fkey')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('provider_specialties_specialty_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_specialties_pkey'))
    )
    op.create_index(op.f('ix_provider_specialties_id'), 'provider_specialties', ['id'], unique=False)
    op.create_table('specialties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('specialties_pkey')),
    sa.UniqueConstraint('name', name=op.f('specialties_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_specialties_id'), 'specialties', ['id'], unique=False)
    # ### end Alembic commands ###
