"""add unique constraint to slots

Revision ID: 24484a4cb6f1
Revises: 461fbedba412
Create Date: 2026-06-17 13:56:10.870477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24484a4cb6f1'
down_revision: Union[str, Sequence[str], None] = '461fbedba412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_slot', 'slots', ['provider_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_slot', 'slots', type_='unique')
    # ### end Alembic commands ###
