"""create patients and audit_log tables

Revision ID: 2fdc6c64180d
Revises: 9c85be897f7d
Create Date: 2026-06-16 21:44:31.127535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdc6c64180d'
down_revision: Union[str, Sequence[str], None] = '9c85be897f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('patients', sa.Column('number', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('patients_email_key'), 'patients', type_='unique')
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_unique_constraint(op.f('patients_email_key'), 'patients', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'user_id')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'number')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
